// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lymmltbqvaqzxkajwgmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5bW1sdGJxdmFxenhrYWp3Z21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzI1MjEsImV4cCI6MjA2ODAwODUyMX0.caIrXG1yuuBMq117orsdohzt8nSfufQ3bIQ1LnKcg9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
